### ISSUE TITLE
connect ECONNREFUSED 127.0.0.1:80

### ISSUE THREAD

**Issue by micheljung** [ory/hydra-login-consent-node#112]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra-login-consent-node/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra-login-consent-node/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

http://localhost:3000/login gives:
```
{ "message": "connect ECONNREFUSED 127.0.0.1:80", "name": "Error", "stack": "Error: connect ECONNREFUSED 127.0.0.1:80\n at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)", "config": { "url": "http://localhost/oauth2/auth/requests/login?login_challenge=undefined", "method": "get", "headers": { "Accept": "application/json, text/plain, */*", "User-Agent": "axios/0.19.2" }, "transformRequest": [ null ], "transformResponse": [ null ], "timeout": 0, "xsrfCookieName": "XSRF-TOKEN", "xsrfHeaderName": "X-XSRF-TOKEN", "maxContentLength": -1 }, "code": "ECONNREFUSED" }
```

### Reproducing the bug

```
docker run --rm -p 3000:3000  oryd/hydra-login-consent-node:v1.11.7
```

Open http://localhost:3000/login

### Relevant log output

```shell
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)
GET /login 500 23.277 ms - 1003
Error: Not Found
    at /usr/src/app/lib/app.js:32:10
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/app/node_modules/express/lib/router/index.js:317:13)
    at /usr/src/app/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)
    at next (/usr/src/app/node_modules/express/lib/router/index.js:275:10)
    at /usr/src/app/node_modules/express/lib/router/index.js:635:15
    at next (/usr/src/app/node_modules/express/lib/router/index.js:260:14)
    at Function.handle (/usr/src/app/node_modules/express/lib/router/index.js:174:3)
    at router (/usr/src/app/node_modules/express/lib/router/index.js:47:12)
```

### Version

1.11.7

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Docker

**Comment by micheljung** [comment]
My bad, I need to set `HYDRA_ADMIN_URL=http://hydra:4445`
