### ISSUE TITLE
Seems to connect to localhost even though HYDRA_ADMIN_URL is set

### ISSUE THREAD

**Issue by wvh** [ory/hydra-login-consent-node#133]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/hydra-login-consent-node/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/hydra-login-consent-node/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Hello,

I'm trying this `hydra-login-consent-node` example on a real Kubernetes cluster I'm setting up, and even though I've got `HYDRA_ADMIN_URL` set to a real hostname, I'm getting this error:

```
request to https://localhost:4445/admin/oauth2/auth/requests/login?login_challenge=abc123 failed, reason: connect ECONNREFUSED 127.0.0.1:4445
```

I logged into the pod and the URL is set properly in the environment, so I'm wondering if that `localhost` URL is hardcoded somewhere.

### Reproducing the bug

- Set up Kubernetes cluster
- Install Hydra
- Install this example
- Point `HYDRA_ADMIN_URL` to the internal service URL for the Hydra `admin` API
- Example returns error about connection failure to `127.0.0.1:4request to https://localhost:4445/admin/oauth2/auth/requests/login?login_challenge=abc123 failed, reason: connect ECONNREFUSED 127.0.0.1:4445

FetchError: request to https://localhost:4445/admin/oauth2/auth/requests/login?login_challenge=abc123 failed, reason: connect ECONNREFUSED 127.0.0.1:4445
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)445` instead of actual service hostname set in `HYDRA_ADMIN_URL`

### Relevant log output

```shell
request to https://localhost:4445/admin/oauth2/auth/requests/login?login_challenge=abc123 failed, reason: connect ECONNREFUSED 127.0.0.1:4445

FetchError: request to https://localhost:4445/admin/oauth2/auth/requests/login failed, reason: connect ECONNREFUSED 127.0.0.1:4445
    at ClientRequest.<anonymous> (/usr/src/app/node_modules/node-fetch/lib/index.js:1455:11)
    at ClientRequest.emit (events.js:182:13)
    at TLSSocket.socketErrorListener (_http_client.js:382:9)
    at TLSSocket.emit (events.js:182:13)
    at emitErrorNT (internal/streams/destroy.js:82:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

### Relevant configuration

```yml
helm install \
	--namespace hydra \
	--set 'hydraAdminUrl=http://oauth-hydra-admin:4445/' \
	--set 'hydraPublicUrl=https://oauth.example.com/' \
	--set 'ingress.enabled=true' \
	hydra-example-idp \
	ory/example-idp
```

### Version

v2.0.2

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Kubernetes with Helm

**Comment by DrBu7cher** [comment]
This is the same case for me, apparently, even though I'm getting the error on IPv6. (`::1::4445`)

**Comment by andremarianiello** [comment]
`HYDRA_ADMIN_URL` needs to be a url (e.g. it needs a scheme, like `http://`). This was the problem for me.

**Comment by gmarcha** [comment]
I had same problem too using [example-idp](https://github.com/ory/k8s/tree/master/helm/charts/example-idp) Helm chart.

I noticed that image tag version was quite old ([v1.4.6](https://github.com/ory/hydra-login-consent-node/blob/f97e1c5a3cbed34e32e879c4a862dae0507576c7/services/hydra.js), referencing HYDRA_ADMIN_URL in this file).

Updating values with image tag version to latest (v2.1.0) solved my problem. A newer version could be added to Helm chart default values ?

**Comment by aeneasr** [comment]
The correct value to set is `HYDRA_ADMIN_URL`
